# Generated by Django 4.0.6 on 2023-01-29 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_amistad',
            name='is_aceptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='amistad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amigos.solicitud_amistad'),
        ),
        migrations.DeleteModel(
            name='Amistad',
        ),
    ]
