# Generated by Django 4.0.6 on 2023-07-28 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amigos', '0002_solicitud_amistad_is_aceptada_alter_mensaje_amistad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud_amistad',
            options={'ordering': ['-created'], 'verbose_name': 'Solicitud-Amistad', 'verbose_name_plural': 'Solicitudes-Amistades'},
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='time_expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 11, 48, 30, 714358)),
        ),
    ]
