# Generated by Django 4.0.6 on 2023-07-28 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amigos', '0005_alter_mensaje_time_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='time_expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 11, 59, 14, 917704)),
        ),
    ]
